### ISSUE TITLE
Problem with landing page on iOS

### ISSUE THREAD

**Issue by srowhani** [schmidyy/boostify#1]
Main page should read, "I am AN" in the case that client chooses "influencer"

**Comment by awaisabir** [comment]
I believe a(n) could work too!

**Comment by schmidyy** [comment]
I'll ping my in-house UX researcher and get this sorted ASAP 👍 Good catch

**Comment by srowhani** [comment]
Thanks. I appreciate the quick response. If you're open to pull requests, I could take a crack at it 😄

**Comment by schmidyy** [comment]
Yes please do @srowhani! I'm swamped tackling a vital bug in the README

**Comment by awaisabir** [comment]
I believe the problem is the fact that 2+2 is 4, minus 1 that's 3 ... `QUICK MATHS`
