### ISSUE TITLE
Indent error

### ISSUE THREAD

**Issue by awaisabir** [schmidyy/boostify#3]
There is an indentation error [here](https://github.com/schmidyy/boostify/blob/master/boostify-client/boostify-client/View%20Controllers/WebModalViewController.swift#L26)

**Comment by schmidyy** [comment]
That's just github being github 🤷🏻‍♂️

**Comment by awaisabir** [comment]
Adding `.editorconfig` file would be a good fix to the problem ☕️

**Comment by srowhani** [comment]
I NEED THIS

**Comment by awaisabir** [comment]
It's a shame this still hasn't been fixed @srowhani

**Comment by srowhani** [comment]
don't get your hopes up this repo is dead
